my_stop<-c("around"  ,  "asked"     ,  "away"  ,    "back"   ,   "behind"  ,  "can"  ,    
           "come"     ,    "didnt" ,    "dont"   ,   "door"  ,
           "even" ,     "eyes"   ,    "face"   ,   "get" ,      "got"    ,   
           "hand"      , "head"     , "hes"       ,"just"  ,   
           "knew"   ,   "know"   ,   "last"   ,   "like"  ,    "littl" ,    "long"   ,  
           "look" ,  "make"   ,    "much"    ,  "never"   ,  "now"      ,
           "one"     ,  "open"   ,   "point"  , "right"   , 
           "said" ,     "saw" ,      "say"    ,   "see"  ,    
           "seem"   ,    "someth"   , "still"  ,   "take"  ,    "tell" ,    
           "thing"     ,"think"   ,  "though",    "thought"   ,"time"   ,   "told" ,  
           "toward"   , "tri"    ,   "turn"   ,   "two"  ,     "voic",
           "want","way","well","will", "harrys", "something", "going", "turned",
           "seemed", "little", "looking")
my_stop_2<-c(my_stop, "another"  , "anything" ,     "came"  ,     "ever"    , 
             "feet"     , "felt"    ,  "first"  ,  "front",  
             "good"   ,   "great"  ,   "heard" ,      "left" ,    
             "let"  ,    "made"  ,    "might" ,    "moment" ,   "mrs",      
             "next"    ,  "people"  ,  "really" ,   "sure" ,     "thats" ,   
             "took"   ,   "trying" , "yes"    ,   "youre")
my_stop_3<-c(my_stop_2, "across" ,    "air"   ,     "arm"  ,      "bed"   ,     "better" ,    "bit" ,      
             "boy" ,       "call"      , "cant"    ,   "care"    ,   "clear"  ,   
             "couldnt" ,     "day"   ,     "done"   ,    "eater" ,    
             "end"      ,  "enough"  ,   "everi",      "floor"  ,   "found" ,    
             "gave"  ,     "give" ,      "ground"    , "hair"    ,   "hall" ,     
             "hard" ,      "hear"   ,    "hed"         , "hous"    ,      
             "keep"     ,    "larg"   ,    "leav"    ,   "loud" ,     
             "man"      ,  "mind"    ,      "mouth"  ,    "must" ,     
             "near"   ,    "night"   ,   "old"    ,    "pass"  ,     "quick" ,     "quiet" ,    
             "quit"  ,     "rai"     ,   "reach"    ,  "rememb"    ,   "second",    
             "seen"    ,   "set"  ,      "shout" ,"side"  ,     "sit" ,       "smile" ,    
             "sound"   ,   "step"     ,  "stood"  ,    "sudden"  ,   "suppo"  ,    
             "upon"  ,     "wait"   ,       "wasnt",     
             "went"   ,   "window"    , "without"  ,  "word"      , "work",   
             "yeah", "every", "find", "hands", "happened", "inside", "house",
             "looked", "mean", "need", "nothing",
             "place", "quite", "pulled",
             "put", "wanted", "inside")
my_stop_4<-c(my_stop_3, "along" ,"already" ,  "always"   ,  "anyone"   ,  "appeared"  ,  "began" ,   
             "believe" ,   "breath"    , "corridor" ,     
             "ear"   ,    "everyon"  , "expect" ,   
             "fell"    ,"full"  ,   
             "gone"    ,  "hold"    ,  "hope"  ,    "howev"   ,  "hurri",    
             "listen"  ,  "madam"   ,  "mani"   ,   "minut" ,  
             "mutter",    "name" ,     "offic" ,    "onto" ,    "past" ,    
             "plea"   ,"rather"  ,  "read" ,    
             "return"   ,   "run"  ,     "sat"  ,     "sir"  ,     "slight"   ,
             "small"  ,   "sort"  ,   "student" ,   
             "top"  ,   "wonder" ,   "wouldnt" ,  "yet", "youv",
             "everyone", "however", "else",
             "large", "many", "opened", "quickly",
             "rons", "sitting", "slightly",
             "standing", "staring", "started",
             "suddenly", "theyre", "tried", "things", "walked",
             "youve", "years", "whats", "reached", "raised",
             "dumbledores", "talking")
my_stop_5<-c(my_stop_4,
             "able"  ,       "added"   ,     "ago"    ,      "almost",
             "alone"  ,     
             "also"     ,    "answer"  ,     "anyway"   ,    "arms",
             "arrived"  ,   
             "ask"   , "bad"   ,  "bagman"  ,    
             "beneath"   , "beside" ,      "best"   , "bill" ,       
             "books"   ,       "called" ,     
             "case"   , "caught"   ,      "ceiling" ,    
             "chair"  ,    "close"  ,      "closed" ,      "cold",        
             "coming"  ,   "common"   ,    "continued" ,   "corner",
             "crabbe", 
             "crowd"   ,  "cup" , "dad" , 
             "days"  ,   "dead"  ,       "dear"  ,  "deep" ,       
             "died"  , "doesnt",       "doors",       
             "dropped"  ,  "dursleys"  ,        
             "ears" ,  "eaters" ,  "either", "entered" ,    
             "everything"   ,"exactly" ,"except"   ,
             "eye" ,        
             "fact"  ,   "far"   ,       "fast"  ,       "father" ,     
             "feel"        , "feeling"    ,        "finally"   ,   "fingers" ,    
             "finished" ,        "five"    ,     "flew"     ,    "followed" ,   
             "foot"    ,  "forward" ,     "four"  ,     
             "getting"      ,"girl"    ,     "given",      
             "grounds"  ,    "hadnt"  ,     
             "hagrids"  ,    "half"  ,    "havent"  ,     "heads",       
             "heart"        ,"held"   ,      "hermiones"    ,"high",
             "hit"    ,     
             "holding"    ,  "home"  , "hurried"  ,    "idea",    "instead",     
             "isnt"  ,       "kept"  ,      "kind" ,       
             "kitchen"    ,        "later"  ,      "lay"  ,       
             "least"    ,    "leave"     ,   "leaving"  ,    "lets",      
             "life"  ,   "looks"  ,        "lost"  ,      
             "lot"   ,       "loudly" ,      "low" , "lying"  ,     
             "magical" ,  "making" , "managed"  ,"matter" ,     
             "maybe"   ,    "minutes"    ,  "morning"   ,   "mother" ,     
             "move"    ,     "moved"  ,      "moving"  ,       "muttered" ,   
             "nearly"  ,     "new"   ,  "nobody"  ,     "nose"  ,      
             "noticed"   ,   "number" , "order"    ,    "others" , "outside" ,    
             "passed" ,     
             "perhaps"     , "person"  ,  "please" ,     
             "pointed"    ,  "pointing"  ,      "quietly"  ,    "ran"  ,       
             "ready"    ,    "real" ,         "remember"  ,   "rest",        
             "returned"   ,    "round"    ,    "running" ,     "saying" ,     
             "says"   ,     "sent"   ,      "several",      "shaking",     
             "shall"  ,   "shes" ,"shook" ,"short" ,  "shoulder",    
             "shouted"    ,  "shut"   ,"sight" ,    
             "since" , "slowly"  ,
             "snapes"   ,    "someone"   ,   "soon" ,  "sorry"  , "speak" ,      
             "spoke"     ,   "staircase"  ,  "stairs"  ,     "stared", "start" ,      
             "stay"      ,   "steps"    ,"stop"  ,  "stopped"  ,   
             "straight"  ,   "students" ,   "supposed"  ,   "taken" , "taking", 
             "talk" ,   "telling" ,  "ten"  ,        "ter" ,        
             "theres"  ,  "thick"   ,     "thinking"     ,"threw" ,    "times" ,      
             "tiny"   ,  "together"  ,   "tonks"  ,      "towards",   
             "trouble"  ,  "try"     ,     "turning"  ,"understand"  , "use" ,        
             "used" ,   "usual"    ,    "voldemorts"   ,"waiting" ,        
             "wands" , "watch"  ,      "watched"  ,    "watching" ,     
             "wearing"  ,"weasleys" , "weve"    ,     "whether" ,     "white" ,      
             "whole"  , "whose"  ,"within" , "wizards" ,    
             "wont"  ,  "words" ,       "world"   ,     "wrong" ,      
             "yeh"  ,  "yelled" ,"youd" , "youll"        
)
my_stop_6<-c(my_stop_5,
             "ahead"  , "angrily",  "angry"  , "apparently", "arent" ,    
             "barely",  "became",  "big", 
             "boys" , "bright", "broke" ,   "broken" ,   "brought" ,  
             "carrying",   "chance",     "chest"  ,   
             "clearly"   , "completely" ,"couple" , "covered"   ,
             "different" , "edge"  ,       
             "evening"   , "expression" ,"faces" , "fine" ,
             "flying"  ,  "friend"  ,   "funny"   ,   "girls" ,    
             "giving"     ,"glanced",    "glasses" ,   "happen", 
             "hell" ,  "horrible" ,  "hour"    ,   "hours"  ,   
             "hundred"   , "hurt"   ,    "important" , "indeed",  
             "known" ,     "knows" ,     "late"   ,    "laugh" ,    
             "led"    ,    "legs"   ,    "less"  ,     "listening",  "longer",    
             "malfoys"  ,  "match"    ,  "may"     ,   "meant" ,    
             "met"      ,  "middle"   ,  "miss"   ,    "muggles"  ,  "mum"  ,
             "neck",      
             "nice"  ,"nodded"   ,  "none"   , "odd"    ,"okay"   ,    "ones" ,     
             "owls"     ,  "pair"  ,     "pale" ,    "pocket" ,   
             "potions"   , "probably"  ,   "pulling"   , "pushed",    
             "question" ,  "reckon"  ,   "repeated"  , "roared",     "rose" ,    
             "seat"   ,    "seconds"  ,  "seized"  ,  "show" ,    
             "slytherins", "smiling" ,      "snapped",    "snitch",     "son",       
             "sounded" ,      "stand"  ,  "stepped"   , "story" , "stuff",     
             "suppose"  ,    "thanks" ,   
             "theyve"  ,   "thin"    ,   "third"   ,   "tonight" ,    
             "trees", "true"   ,  "trunk" , "walking"   , "walls" ,    
             "week"    ,   "wide"    ,  "windows"  ,  "wizarding"  ,"woman" ,  
             "worse", "young" ) 
